services:
    sirian_signer.filter.base64:
        class: Sirian\Signer\Filter\Base64Filter
        tags:
            - {name: sirian_signer.filter, alias: base64}

    sirian_signer.filter.json:
        class: Sirian\Signer\Filter\JsonFilter
        tags:
            - {name: sirian_signer.filter, alias: json}

    sirian_signer.filter.gz:
        class: Sirian\Signer\Filter\GzFilter
        tags:
            - {name: sirian_signer.filter, alias: gz}

    sirian_signer.filter_registry:
        class: Sirian\Signer\Filter\FilterRegistry

    sirian_signer.filter.chain:
        class: Sirian\Signer\Filter\ChainFilter
        arguments: [@sirian_signer.filter_registry, ~]

    sirian_signer.manager:
        class: Sirian\Signer\Manager
        arguments: [~, ~, @sirian_signer.filter.chain]

    sirian_signer.authentication.provider:
        class: Sirian\SignerBundle\Security\Authentication\Provider\SignedRequestProvider
        arguments: [@security.user_checker, ~]
        public: false

    sirian_signer.authentication.listener:
        class: Sirian\SignerBundle\Security\Firewall\SignedRequestListener
        arguments: [@sirian_signer.manager, @security.context, @security.authentication.manager, ~, ~, ~]
        public: false
        abstract: true

